### ISSUE TITLE
Resource Not Found error after close and relaunch the app

### ISSUE THREAD

**Issue by VincentAP** [android/app-bundle-samples#109]
I am using <include-dynamic> in my main_navigation.xml for dynamic-feature module. After i downloaded the uploaded .aab to play store for internal testing, in the first time i launched the app all works perfectly (open a fragment from the DFM, then close the fragment and reopen the fragment and so on). But after i close the app and relaunched it, everytime i try to reopen the fragment, the app crash with Resource Not Found error for the destination of the navigation graph inside the DFM. I don't understand how could this happened. I mean, the first time installation the works just fine, but after close and relaunch the app, it crashes. Please help. (Sorry for my bad english).

**Comment by keyboardsurfer** [comment]
Can you please share the logs you're seeing as the application crashes with us?

**Comment by Faisal-Naseer** [comment]
The same is happening with me . the app works fine after downloading dynamic module but as soon as i restart my app.
theres a button on my splash screen which navigates to dynamic feature
Heres the code that i copied from google dynamic features sample repo
```
private fun onSuccessfulLoad(moduleName: String, launch: Boolean) {
    if (launch) {
        when (moduleName) {
            quranpagesfeatures -> launchActivity(mainActivity)
            /*   moduleJava -> launchActivity(javaSampleClassname)
               moduleNative -> launchActivity(nativeSampleClassname)*/
        }
    }

}
```
I have already overridden the code in BaseActivity and App class 
```

 open class BaseActivity: AppCompatActivity() {
    override fun attachBaseContext(newBase: Context?) {
        super.attachBaseContext(newBase)
        SplitCompat.install(this)
    }
}
 public class App extends Application {
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        SplitCompat.install(base);
    }
}

```
But its crashing when i revisit the application

The Exception thats occurring in my logs Crashlytics


> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qp.readquranoffline.holybookreading/com.mycode.pagesfeature.activities.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7e010000
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3621)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3866)
>        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
>        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:268)
>        at android.app.ActivityThread.main(ActivityThread.java:8004)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
> 
> Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7e010000
>        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:248)
>        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2400)
>        at android.content.res.Resources.getAnimation(Resources.java:1277)
>        at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:138)
>        at com.mycode.quranpagesfeature.activities.MainActivity.onCreate(MainActivity.kt:158)
>        at android.app.Activity.performCreate(Activity.java:8058)
>        at android.app.Activity.performCreate(Activity.java:8042)
>        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1315)
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3594)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3866)
>        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
>        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:268)
>        at android.app.ActivityThread.main(ActivityThread.java:8004)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
