### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by javalue** [android/app-bundle-samples#117]
when i add com.google.android.play:core:1.10.3,i lanuch app happened this crash.
but it happened in release apk,the debug apk is ok.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aaa/com.aaa.SplashActivity}: android.content.res.Resources$NotFoundException: Drawable com.aaa:drawable/abc_vector_test with resource ID #0x7f080054
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2904)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2986)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6784)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)

**Comment by javalue** [comment]
testing all day
i have found res in apk is very small,normal like 2-3mb, but now is 500kb
in my test,
when i set shrinkResources = false,it's ok

**Comment by javalue** [comment]
build/generate signed apk/.... it will crash
gradle/android/tasks/install/installRelease..... it will ok

**Comment by Dheeraj-tb** [comment]
dynamic feature is also implemented in your project?

**Comment by Dheeraj-tb** [comment]
@javalue any luck?

**Comment by digitalillusion** [comment]
I had minifyEnabled true in release target and this produced NotFoundExceptions
