### ISSUE TITLE
Error code -3

### ISSUE THREAD

**Issue by Virczek** [android/app-bundle-samples#12]
Hello, I looking solution for:
```
Non-fatal Exception: com.google.android.play.core.install.InstallException: Install Error: -3
       at com.google.android.play.core.appupdate.i.b(i.java:6)
       at com.google.android.play.core.internal.o.a(o.java:6)
       at com.google.android.play.core.internal.j.onTransact(j.java)
       at android.os.Binder.execTransact + 446(Binder.java:446)
```
Unfortunately I didn't find at docs & issues any information, about error -3. What's reason of that?

Device: 
LGE Nexus 4
Android 5.1.1
Free disc space: 4.56 GB
Free ram: 926 MB

**Comment by keyboardsurfer** [comment]
The documentation on [InstallException](https://developer.android.com/reference/com/google/android/play/core/install/model/InstallErrorCode#error_api_not_available) mentions that this is `ERROR_API_NOT_AVAILABLE`.
