### ISSUE TITLE
ContentProvider in dynamic module

### ISSUE THREAD

**Issue by pendai** [android/app-bundle-samples#128]
I have declared ContentProvider in my dynamic module's manifest 。 this would result in ClassNotFoundException.(bad english)
     <dist:module
        dist:instant="false"
        dist:title="@string/title">
        <dist:delivery>
            <dist:install-time >
                <dist:conditions>
                          <dist:user-countries dist:exclude="false">
                                 <dist:country dist:code="JP"/>
			 </dist:user-countries>
                </dist:conditions>
            </dist:install-time>
        </dist:delivery>
        <dist:fusing dist:include="false" />
    </dist:module>
  <application>
        <provider
            android:name="com.exp.initializer.MobileInitializeProvider"
            android:authorities="${applicationId}.MobileInitializeProvider"
            android:exported="false" />
    </application>
    
    trace:
        java.lang.RuntimeException: Unable to get provider com.exp.initializer.MobileInitializeProvider: java.lang.ClassNotFoundException: Didn't find class "com.exp.initializer.MobileInitializeProvider" on path: DexPathList[[zip file "/data/app/com.block.puzzle.game.wooden-s38mQmfCLB4I1rmGAkXfDg==/base.apk", zip file "/data/app/com.block.puzzle.game.wooden-s38mQmfCLB4I1rmGAkXfDg==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.block.puzzle.game.wooden-s38mQmfCLB4I1rmGAkXfDg==/lib/arm64, /data/app/com.block.puzzle.game.wooden-s38mQmfCLB4I1rmGAkXfDg==/base.apk!/lib/arm64-v8a, /data/app/com.block.puzzle.game.wooden-s38mQmfCLB4I1rmGAkXfDg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7191)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6669)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6586)
        at android.app.ActivityThread.access$1500(ActivityThread.java:233)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by pendai** [comment]
![image](https://github.com/android/app-bundle-samples/assets/11819764/4a8f8742-bb01-4da8-a843-289069d30ade)
![image](https://github.com/android/app-bundle-samples/assets/11819764/3965d5ef-7701-4e19-be49-8132872a991c)
