### ISSUE TITLE
Error receiving broadcast Intent { act=com.google.android.play.core.splitinstall.receiver.SplitInstallUpdateIntentService

### ISSUE THREAD

**Issue by beyondckw** [android/app-bundle-samples#15]
```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.play.core.splitinstall.receiver.SplitInstallUpdateIntentService flg=0x40000010 pkg=com.xxx.xxx (has extras) } in com.google.android.play.core.a.c@f8b72c9
       at android.app.LoadedApk$ReceiverDispatcher$Args.run + 932(LoadedApk.java:932)
       at android.os.Handler.handleCallback + 815(Handler.java:815)
       at android.os.Handler.dispatchMessage + 104(Handler.java:104)
       at android.os.Looper.loop + 207(Looper.java:207)
       at android.app.ActivityThread.main + 5788(ActivityThread.java:5788)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 789(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main + 679(ZygoteInit.java:679)
Caused by java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry + 787(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next + 814(HashMap.java:814)
       at com.google.android.play.core.listener.a.a$1385ff(a.java)
       at com.google.android.play.core.splitinstall.k.a(k.java:2000)
       at com.google.android.play.core.splitinstall.k.a(k.java:2000)
       at com.google.android.play.core.splitinstall.SplitInstallSessionState.status(SplitInstallSessionState.java:2000)
       at com.google.android.play.core.splitinstall.k.a(k.java:2000)
       at com.google.android.play.core.splitinstall.k.a(k.java:2000)
       at com.google.android.play.core.listener.b.onReceive(b.java)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run + 922(LoadedApk.java:922)
       at android.os.Handler.handleCallback + 815(Handler.java:815)
       at android.os.Handler.dispatchMessage + 104(Handler.java:104)
       at android.os.Looper.loop + 207(Looper.java:207)
       at android.app.ActivityThread.main + 5788(ActivityThread.java:5788)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 789(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main + 679(ZygoteInit.java:679)
```

**Comment by keyboardsurfer** [comment]
Can you please add what you're doing to trigger this error?
If this is on your own code, please file an issue at https://goo.gle/app-bundles-issue and link it here.

**Comment by keyboardsurfer** [comment]
We need your input to act on this issue.
This issue will be closed soon unless there is further actionable input.

**Comment by ammar-ali** [comment]
@keyboardsurfer so I was really busy at some stuff how did i trigger it >

I installed the module then uninstalled it after executing SQL queries  example I have put queries file in the assets folder of the dynamic module once I executed those queries I don't need the file or the module anymore so when i uninstalled it, it crashed every single time

**Comment by keyboardsurfer** [comment]
What crash did you see at which exact call you were making?

**Comment by ammar-ali** [comment]
Can you spare. Me some time i will get back to ASAP

**Comment by b95505017** [comment]
I'm using dynamic navigation library and see the same issue in crashlytics on Android 9

```
Fatal Exception: java.lang.RuntimeException
Error receiving broadcast Intent { act=com.google.android.play.core.splitinstall.receiver.SplitInstallUpdateIntentService flg=0x40280010 pkg=xxx.xxx.xxx (has extras) } in f7.i.a.g.a.g.b@43265b5
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0
Caused by android.content.res.Resources$NotFoundException
xxx.xxx.xxx.xxx:navigation/xxx
androidx.navigation.dynamicfeatures.DynamicIncludeGraphNavigator.replaceWithIncludedNav (DynamicIncludeGraphNavigator.java:88)
```

**Comment by keyboardsurfer** [comment]
@b95505017 this hints in the direction that you're passing in a wrong resource package name.
Make sure to use the one declared in the dynamic feature's AndroidManifest.

**Comment by b95505017** [comment]
@keyboardsurfer Most of the time they work as intended. I can't reproduce on my side buy received that crash in Crashlytics.

**Comment by nicemak** [comment]
can you help me with this?

`java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.play.core.splitinstall.receiver.SplitInstallUpdateIntentService flg=0x40280010 pkg=com.boschpharma.ikonnect.cardiacare (has extras) } in com.google.android.play.core.listener.zzb@81b20dd
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1940)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.math.BigDecimal.<init>(BigDecimal.java:518)
	at java.math.BigDecimal.<init>(BigDecimal.java:401)
	at java.math.BigDecimal.<init>(BigDecimal.java:834)
	at com.boschpharma.ikonnect.cardiacare.view.ui.presentation.Folders.listener$lambda-0(Folders.kt:193)
	at com.boschpharma.ikonnect.cardiacare.view.ui.presentation.Folders.$r8$lambda$FEaDTLOC-2g5C2cCmuTGlWGZ4KQ(Unknown Source:0)
	at com.boschpharma.ikonnect.cardiacare.view.ui.presentation.Folders$$ExternalSyntheticLambda5.onStateUpdate(Unknown Source:4)
	at com.google.android.play.core.listener.zzc.zzi(com.google.android.play:core@@1.10.3:2)
	at com.google.android.play.core.splitinstall.zzx.zzm(com.google.android.play:core@@1.10.3:3)
	at com.google.android.play.core.splitinstall.zzx.zza(com.google.android.play:core@@1.10.3:5)
	at com.google.android.play.core.listener.zzb.onReceive(com.google.android.play:core@@1.10.3:1)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1902)
	... 9 more
`

**Comment by KennethCJ** [comment]
您发的邮件我已收到 我会尽快回复你

**Comment by MichaelJokAr** [comment]
Any one has fixed this?

**Comment by KennethCJ** [comment]
您发的邮件我已收到 我会尽快回复你
