### ISSUE TITLE
crash in some case

### ISSUE THREAD

**Issue by liangxiwei** [android/app-bundle-samples#3]
1.open java module
2.cant open,just stay in loading page.

after some minutes,crash happen.

```
09-09 16:55:54.844 23850 23850 E AndroidRuntime: FATAL EXCEPTION: main
09-09 16:55:54.844 23850 23850 E AndroidRuntime: Process: com.google.android.samples.dynamicfeatures.ondemand, PID: 23850
09-09 16:55:54.844 23850 23850 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.play.core.splitinstall.receiver.SplitInstallUpdateIntentService flg=0x40200010 pkg=com.google.android.samples.dynamicfeatures.ondemand (has extras) } in com.google.android.play.core.listener.b@9326932
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1329)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6942)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: Caused by: java.util.UnknownFormatConversionException: Conversion = 'i'
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2781)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2811)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at java.util.Formatter.parse(Formatter.java:2557)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2504)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2458)
09-09 16:55:54.844 23850 23850 E AndroidRuntime: 	at java.lang.String.format(String.java:2814)
```

**Comment by keyboardsurfer** [comment]
Thanks for reporting this problem.
I followed these steps but can't reproduce the issue.
Please re-open if the issue still persists.

**Comment by MichaelJokAr** [comment]
How did you fix this?
