### ISSUE TITLE
Problem with showing notification from dynamic feature

### ISSUE THREAD

**Issue by vadimp56** [android/app-bundle-samples#41]
Problem description:
After downloading and installing dynamic module i trying to show notification inside dynamic module. The app crashed even after restart while trying to show notification. For Small Icon resource i use drawable from the same module. But notification not showing and app crash with stackTrace (see attachments). If i use drawable from base module everything works well.

This is sample with current error https://github.com/vadimp56/dynamic-feature-notification-sample

Instruction for reproduction problem:
Install sample app using app-aab.zip (in attachements)
Grant Storage permission for Android 6.0 or above
Unzip app-debug.zip 
Push unzipped app-debug folder to device by path /sdcard
Start sample app and click to button FEATURE MODULE NOTIFICATION

[app-debug.zip](https://github.com/android/app-bundle-samples/files/4070639/app-debug.zip)
[app-aab.zip](https://github.com/android/app-bundle-samples/files/4070643/app-aab.zip)

Stacktrace:

```
android.content.res.Resources$NotFoundException: Resource ID #0x7e030000
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:905)
        at android.content.res.Resources.getDrawable(Resources.java:845)
        at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:370)
        at android.graphics.drawable.Icon.loadDrawable(Icon.java:323)
        at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:434)
        at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:408)
        at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:392)
        at com.android.systemui.statusbar.StatusBarIconView.updateDrawable(StatusBarIconView.java:370)
        at com.android.systemui.statusbar.StatusBarIconView.set(StatusBarIconView.java:330)
        at com.android.systemui.statusbar.notification.collection.NotificationEntry.createIcons(NotificationEntry.java:347)
        at com.android.systemui.statusbar.notification.collection.NotificationRowBinderImpl.inflateViews(NotificationRowBinderImpl.java:134)
        at com.android.systemui.statusbar.notification.NotificationEntryManager.addNotificationInternal(NotificationEntryManager.java:381)
        at com.android.systemui.statusbar.notification.NotificationEntryManager.addNotification(NotificationEntryManager.java:396)
        at com.google.android.systemui.statusbar.NotificationEntryManagerGoogle.addNotification(NotificationEntryManagerGoogle.java:76)
        at com.android.systemui.statusbar.NotificationListener.lambda$onNotificationPosted$1$NotificationListener(NotificationListener.java:118)
        at com.android.systemui.statusbar.-$$Lambda$NotificationListener$NvFmU0XrVPuc5pizHcri9I0apkw.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by keyboardsurfer** [comment]
Thanks for filing this issue.
This is not an issue with this sample, so please file it at [issuetracker.google.com](https://issuetracker.google.com/issues/new?component=192633&template=843412) and link it here so I can help routing it correctly.

**Comment by keyboardsurfer** [comment]
We need your input to act on this issue.
This issue will be closed soon unless there is further actionable input.
