### ISSUE TITLE
Problem with instrumentation tests from feature module

### ISSUE THREAD

**Issue by maarten195** [android/app-bundle-samples#42]
Since commit [Bump versions](https://github.com/android/app-bundle-samples/commit/50f43dac84ce98db8967b56a62fa3973e5859d7d) the instrumentation tests no longer work (while using the command line `./gradlew connectedAndroidTest --no-parallel`). It seems that updating the gradle version causes this error. The instrumentation tests work using version 3.4.1 and they don't work with the bumped versions 3.6.0-beta05 and 4.0.0-alpha07.

If I run `./gradlew connectedAndroidTest --no-parallel` on [latest commit](https://github.com/android/app-bundle-samples/commit/57a4efd0a24c2c43cabf19225b192e24cb7a4a6b) without any changes to the code I get the following stacktrace: 

```
> Task :features:assets:processDebugAndroidTestResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':features:assets:processDebugAndroidTestResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/maartenvanwalstijn/.gradle/caches/transforms-2/files-2.1/14817984f8ff4b589cc7f547995b1e7b/core-1.6.4/AndroidManifest.xml:9:5-278: AAPT: error: resource style/Theme.PlayCore.Transparent (aka com.google.android.samples.dynamicfeatures.ondemand.assets.test:style/Theme.PlayCore.Transparent) not found.
```

If I run `./gradlew connectedAndroidTest --no-parallel` on [Bump version commit](https://github.com/android/app-bundle-samples/commit/50f43dac84ce98db8967b56a62fa3973e5859d7d), while adding the ndkversion,  I get the following stacktrace. In this build I used the gradle version 3.6.0-beta05.

```
> Task :app:connectedDebugAndroidTest
Starting 1 tests on Pixel_2_API_28(AVD) - 9

> Task :features:native:externalNativeBuildDebug
Build hello-jni_armeabi-v7a
ninja: Entering directory /Users/maartenvanwalstijn/app-bundle-samples/DynamicFeatures/features/native/.cxx/cmake/debug/armeabi-v7a'
ninja: no work to do.
Build hello-jni_arm64-v8a
ninja: Entering directory /Users/maartenvanwalstijn/app-bundle-samples/DynamicFeatures/features/native/.cxx/cmake/debug/arm64-v8a'
ninja: no work to do.
Build hello-jni_x86
ninja: Entering directory /Users/maartenvanwalstijn/app-bundle-samples/DynamicFeatures/features/native/.cxx/cmake/debug/x86'
ninja: no work to do.
Build hello-jni_x86_64
ninja: Entering directory /Users/maartenvanwalstijn/app-bundle-samples/DynamicFeatures/features/native/.cxx/cmake/debug/x86_64'
ninja: no work to do.

> Task :features:initialInstall:connectedDebugAndroidTest
The APKs have been extracted in the directory: /var/folders/w2/w24g2xcs6_x465bn5qhhr8v40000gn/T/apkSelect1907910629298317514
Starting 1 tests on Pixel_2_API_28(AVD) - 9

com.google.android.samples.dynamicfeatures.InitialInstallActivityTest > launchKotlinSampleActivity[Pixel_2_API_28(AVD) - 9] FAILED 
        java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
        at androidx.appcompat.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:756)
[InstrumentationResultParser]: Ignoring repeated failed event for com.google.android.samples.dynamicfeatures.InitialInstallActivityTest#launchKotlinSampleActivity. Stack: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.samples.dynamicfeatures.ondemand/com.google.android.samples.dynamicfeatures.InitialInstallActivity}: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
at androidx.appcompat.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:756)
at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
at androidx.appcompat.app.AppCompatDelegateImpl.<init>(AppCompatDelegateImpl.java:260)
at androidx.appcompat.app.AppCompatDelegate.create(AppCompatDelegate.java:182)
at androidx.appcompat.app.AppCompatActivity.getDelegate(AppCompatActivity.java:520)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
at com.google.android.samples.dynamicfeatures.InitialInstallActivity.onCreate(InitialInstallActivity.kt:27)
at android.app.Activity.performCreate(Activity.java:7136)
at android.app.Activity.performCreate(Activity.java:7127)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:674)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
... 11 more

Tests on Pixel_2_API_28(AVD) - 9 failed: Instrumentation run failed due to Process crashed.

> Task :features:initialInstall:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.
```

If I downgrade only the gradle version to 3.4.1 (either [latest commit](https://github.com/android/app-bundle-samples/commit/57a4efd0a24c2c43cabf19225b192e24cb7a4a6b) or [Bump version commit](https://github.com/android/app-bundle-samples/commit/50f43dac84ce98db8967b56a62fa3973e5859d7d)) the instrumentation tests are running again.

**Comment by CristianGM** [comment]
I had the same issue, we are keeping the project on AGP 3.4.2
Using any newer AGP fails, I got it working by adding `androidTestImplementation(project(":..."))` for each module we need resources from, but, then it crashed on execution on each test with:

> Attempt to invoke virtual method 'void androidx.appcompat.widget.ContentFrameLayout.setId(int)' on a null object reference
>  at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:845)
>  at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
>  at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
>  at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
>  at com.anuntis.fotocasa.v5.base.bottombar.view.BottomBarActivity.onCreate(BottomBarActivity.kt:30)
 
I feel like running UI Tests on dynamic features, sadly, hasn't been really part of the plan at all.

**Comment by keyboardsurfer** [comment]
We're aware of this and have been working on a fix that will be rolled out with one of the next Android Studio 4.0 canary builds.

**Comment by andresfabreu** [comment]
is it live already?

**Comment by jwitwit** [comment]
Dear team, 

We would appreciate any updates on this issue. Thanks in advance.

**Comment by andresfabreu** [comment]
Still not working, I tried today with:

```
Android Studio 4.1 Canary 6
Build #AI-193.6911.18.41.6381907, built on April 9, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 8108M
Cores: 12
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Lombook Plugin, org.jetbrains.kotlin, com.thoughtworks.gauge, org.intellij.plugins.markdown, wu.seal.tool.jsontokotlin)
```

And I get the error, running through AS, but if I run via ./gradlew it works, but I'm not able to debug:

```
INSTRUMENTATION_FAILED: myapp.qa.test/android.test.InstrumentationTestRunnerandroid.util.AndroidException: INSTRUMENTATION_FAILED: myapp.qa.test/android.test.InstrumentationTestRunner

Error Unable to find instrumentation info for: ComponentInfo{myapp.qa.test/android.test.InstrumentationTestRunner}

idActivityManagerService        at com.android.commands.am.Instrument.run(Instrument.java:486)
        at com.android.commands.am.Am.runInstrument(Am.java:194)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```

**Comment by keyboardsurfer** [comment]
@andresfabreu can you verify the issue on the samples in this repository?

**Comment by andresfabreu** [comment]
@keyboardsurfer I was able to run with the Beta version, thx.

```
Android Studio 4.0 Beta 4
Build #AI-193.6911.18.40.6348893, built on March 30, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 12
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Lombook Plugin, org.jetbrains.kotlin, com.thoughtworks.gauge, org.intellij.plugins.markdown, wu.seal.tool.jsontokotlin
```
Now I'm able to run instrumental and unit tests with dynamic features.
