### ISSUE TITLE
SplitCompat.installActivity() or SplitCompat.install()

### ISSUE THREAD

**Issue by tprochazka** [android/app-bundle-samples#56]
Why you are using `SplitCompat.install()` in activity here?

https://github.com/android/app-bundle-samples/blob/71d082c2637ae6be41a9efe59256557939b2853b/DynamicFeatures/app/src/main/java/com/google/android/samples/dynamicfeatures/BaseSplitActivity.kt#L32

According documentation it should be `SplitCompat.installActivity()` right?

In my app, I have still issue with missing resources in dynamic modules. I'm using `SplitCompat.install()` in application class  and `SplitCompat.installActivity()` in every activity of dynamic module. But it still crashing, the only difference I found it this.

**Comment by keyboardsurfer** [comment]
Can you reproduce the issue with the sample code given in this repository or is it an issue occurring in your own implementation?

**Comment by tprochazka** [comment]
No, it happens only in my application. So I tried to compare my app with this sample and everything is the same, only SplitCompat.install() in your activity is a difference, but I tried the same in my app and it still doesn't work.

It always crashes on some MissingResourceException, and it looks that not on my resources but on 3rd library resource, for example, I'm using Chrome Cast support in my app and it failing on 

```
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7e0a0070
        at android.content.res.Resources.getText(Resources.java:363)
        at android.content.res.Resources.getString(Resources.java:456)
        at androidx.mediarouter.media.SystemMediaRouteProvider$JellybeanImpl.<init>(SystemMediaRouteProvider.java:271)
2020-05-13 00:13:44.816 23246-23246/? E/AndroidRuntime:     at androidx.mediarouter.media.SystemMediaRouteProvider$JellybeanMr1Impl.<init>(SystemMediaRouteProvider.java:740)
        at androidx.mediarouter.media.SystemMediaRouteProvider$JellybeanMr2Impl.<init>(SystemMediaRouteProvider.java:813)
        at androidx.mediarouter.media.SystemMediaRouteProvider$Api24Impl.<init>(SystemMediaRouteProvider.java:871)
        at androidx.mediarouter.media.SystemMediaRouteProvider.obtain(SystemMediaRouteProvider.java:55)
        at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter.<init>(MediaRouter.java:1987)
        at androidx.mediarouter.media.MediaRouter.getInstance(MediaRouter.java:263)
        at androidx.mediarouter.app.MediaRouteButton.<init>(MediaRouteButton.java:128)
        at androidx.mediarouter.app.MediaRouteButton.<init>(MediaRouteButton.java:121)
```

I already spent 5 days on it.

**Comment by keyboardsurfer** [comment]
this sounds similar to [this bug](https://issuetracker.google.com/issues/148404341). Can you provide us with more information there, so we can help to chase it up and hopefully resolve it if it's on our end.

**Comment by tprochazka** [comment]
For me, it happens at least on Android 9 and 10. So not only A6.
What kind of information can help you?
I think that the best would be a testing project.

**Comment by keyboardsurfer** [comment]
Yes, a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) would be great.
To minimize overhead I recommend using the sample in this repository and making adjustments to it.

**Comment by tprochazka** [comment]
MVCE is sadly usually very complicated. I tried to put some parts of my app to your sample and it works. I also tried to put your Activity to my app and it also works. It's for example limitation that you can't use any Context in the app? Should works, for example, all variants inside of the activity?

        applicationContext.getText()
        baseContext.getText()
        getText()

**Comment by keyboardsurfer** [comment]
At this point I've got to ask you to head over to [StackOverflow](stackoverflow.com) with essential information on the issue you're facing, as the sample at hand seems to be working for you.
