### ISSUE TITLE
Custom View cannot preview on Android Studio 3.4.2

### ISSUE THREAD

**Issue by watsaponk** [android/app-bundle-samples#6]
I create custom view and use LayoutInflater but Android Studio cannot preview my custom view when use it on fragment or activity 
basically it work fine while running on device or emulator just preview issue

```
class FraudWarningBox : ConstraintLayout {
    constructor(context: Context?) : this(context, null)
    constructor(context: Context?, attrs: AttributeSet?) : this(context, attrs, 0)
    constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {
        val view = LayoutInflater.from(context).inflate(R.layout.view_fraud_warning_box, this, false)
        addView(view)
    }
}
```

```
android.content.res.Resources$NotFoundException: Could not resolve resource value: 0x7D030002. Or the resolved value was not of type layout as expected.
	at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1145)
	at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1121)
	at android.content.res.Resources_Delegate.getLayout(Resources_Delegate.java:497)
	at android.content.res.Resources.getLayout(Resources.java:1155)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
	at com.app.kaidee.addetail.uicomponent.FraudWarningBox.<init>(FraudWarningBox.kt:15)
	at com.app.kaidee.addetail.uicomponent.FraudWarningBox.<init>(FraudWarningBox.kt:13)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:403)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:186)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:144)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:309)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:418)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:429)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:333)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:326)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:391)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:195)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:540)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:666)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by keyboardsurfer** [comment]
Please ask this as a question on StackOverflow and link it here.

**Comment by watsaponk** [comment]
@keyboardsurfer ok
