### ISSUE TITLE
Dynamic Feature Module giving Resource Not Found Exception when using webview

### ISSUE THREAD

**Issue by rishabhMaltare** [android/app-bundle-samples#82]
Hi, 

I have an app live on play store and I am using the Dynamic delivery option for a module.  Till now, this module was working fine. In the last release, I had added Webview in one of the screens in this module. Now it started throwing crashes whenever I navigate to that screen. And, when I removed the webview from the code, it is working fine again. And from the stack trace it is not possible to get that, it is causing the crash because of webview. 

I searched on the google and stumbled upon this link: https://chromium.googlesource.com/chromium/src.git/+/master/docs/android_dynamic_feature_modules.md

it says that, webview is not supported in DFMs.

So, I am not sure whether this is a known issue as I couldn't find about this limitation on official android docs.

This is the stacktrace, I am getting: 

```

Fatal Exception: android.view.InflateException: Binary XML file line #104: Binary XML file line #104: Error inflating class <unknown>
Caused by android.view.InflateException: Binary XML file line #104: Error inflating class <unknown>

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at com.sliceit.hns.helpAndSupport.view.ArticleFragment.onCreateView(ArticleFragment.kt:83)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)


Caused by android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7e010012

Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7e010012
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:228)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:687)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
       at android.content.res.Resources.loadDrawable(Resources.java:972)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:931)
       at android.view.View.<init>(View.java:4226)
       at android.view.ViewGroup.<init>(ViewGroup.java:603)
       at android.view.ViewGroup.<init>(ViewGroup.java:599)
       at android.view.ViewGroup.<init>(ViewGroup.java:595)
       at androidx.constraintlayout.widget.ConstraintLayout.<init>(ConstraintLayout.java:575)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at com.sliceit.hns.helpAndSupport.view.ArticleFragment.onCreateView(ArticleFragment.kt:83)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by keyboardsurfer** [comment]
This issue is tracked [here](https://issuetracker.google.com/162779750) instead of on this sample.
